# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class SubdataSelectionTester(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login'):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = None
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc)

    def get_object_subset(self, sub_object_ids, context=None):
        """
        :param sub_object_ids: instance of list of type "SubObjectIdentity"
           -> structure: parameter "ref" of String, parameter "included" of
           list of String
        :returns: instance of list of type "ObjectData" -> structure:
           parameter "data" of unspecified object
        """
        return self._client.call_method(
            'SubdataSelectionTester.get_object_subset',
            [sub_object_ids], self._service_ver, context)

    def hello_world(self, name, context=None):
        """
        :param name: instance of String
        :returns: instance of String
        """
        return self._client.call_method(
            'SubdataSelectionTester.hello_world',
            [name], self._service_ver, context)

    def status(self, context=None):
        return self._client.call_method('SubdataSelectionTester.status',
            [], self._service_ver, context)
